runtime: custom       
env: flex
entrypoint: gunicorn -b :$PORT main:app    

runtime_config:
  python_version: 3

endpoints_api_service:
  name: test-1-179209.appspot.com       
#  rollout_strategy: managed            
  config_id: 2018-08-30r2    
